apiVersion: batch/v1
kind: Job
metadata:
  name: app-slack-notification
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  labels:
    app: spring-petclinic
    app.kubernetes.io/component: web
    app.kubernetes.io/instance: spring-petclinic
    app.kubernetes.io/name: spring-petclinic
    app.kubernetes.io/part-of: spring-petclinic
    app.openshift.io/runtime: java
spec:
  template:
    spec:
      containers:
      - name: slack-notification
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "--data-urlencode"
          - "payload={\"channel\": \"#ihis-developer\", \"text\": \"App Sync succeeded\"}"
          - "$(SLACK)"
        env:
        - name: SLACK
          valueFrom:
            secretKeyRef:
              name: slack
              key: slack-text
      restartPolicy: Never
  backoffLimit: 2
